version: '3.8'

services:
  app:
    build: .
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - "8503:8503"
    volumes:
      - ${LOCAL_DATA_DIR}:/app/data:ro
    environment:
      - DATA_DIR=/app/data
      - POSTGRES_HOST=postgis
      - POSTGRES_PORT=5433
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  postgis:
    image: postgis/postgis:17-3.5
    container_name: postgis
    restart: always
    command: -p 5433
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - '5433:5433'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5433"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:9.5
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '8888:80'
    volumes:
      - ./infra/servers.json:/pgadmin4/servers.json:ro
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgis

volumes:
  postgresql_data:
  pgadmin-data:

